Iterating Arrays: Iterating means going through elements one by one.

Iterating 1-D array:

In [1]:
import numpy as np

arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


Iterating 2-D Arrays:

In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    print(row)

[1 2 3]
[4 5 6]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


Iterating 3-D Arrays

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()

In [ ]:
import numpy as np

arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]]])
         
for x in np.nditer(arr): # Row-major order (C) -> default
    print(x, end=" ")
print()

for x in np.nditer(arr, order='F'): # Column-major order (F) -> Fortran style
    print(x, end=" ")

(2, 2, 2)
1 2 3 4 5 6 7 8 
1 5 3 7 2 6 4 8 

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]): # : -> select all rows, ::2 - > select every second column, starting at index 0
    print(x)

1
3
5
7


Enumerated Iteration Using ndenumerate()- Enumeration means mentioning sequence number of somethings one by one.

In [12]:
import numpy as np

arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
   print(idx, x)
   

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
