In [ ]:
import numpy as np

arr = np.random.randint(1, 10, size = (10, 5)) # sample = 10, feature = 5
print(arr)
print(arr.shape)

arr2 = arr.reshape(5, 10)
print(arr2)

flattening = arr2.flatten()
print(flattening)

column_wise_flattening = np.ravel(arr2, order = 'F')
print(column_wise_flattening)

row_wise_flattening = np.ravel(arr2, order = 'C')
print(row_wise_flattening)

[[5 2 7 7 2]
 [7 5 4 7 7]
 [8 5 8 3 5]
 [1 8 6 4 5]
 [3 3 5 5 1]
 [4 8 7 1 4]
 [2 1 6 2 8]
 [6 1 7 7 5]
 [4 6 2 8 8]
 [5 8 7 2 9]]
(10, 5)
[[5 2 7 7 2 7 5 4 7 7]
 [8 5 8 3 5 1 8 6 4 5]
 [3 3 5 5 1 4 8 7 1 4]
 [2 1 6 2 8 6 1 7 7 5]
 [4 6 2 8 8 5 8 7 2 9]]
[5 2 7 7 2 7 5 4 7 7 8 5 8 3 5 1 8 6 4 5 3 3 5 5 1 4 8 7 1 4 2 1 6 2 8 6 1
 7 7 5 4 6 2 8 8 5 8 7 2 9]
[5 8 3 2 4 2 5 3 1 6 7 8 5 6 2 7 3 5 2 8 2 5 1 8 8 7 1 4 6 5 5 8 8 1 8 4 6
 7 7 7 7 4 1 7 2 7 5 4 5 9]
[5 2 7 7 2 7 5 4 7 7 8 5 8 3 5 1 8 6 4 5 3 3 5 5 1 4 8 7 1 4 2 1 6 2 8 6 1
 7 7 5 4 6 2 8 8 5 8 7 2 9]


In [ ]:
a = np.random.randint(1, 10, size = (3, 3))
b = np.random.randint(10, 20, size = (3, 3))

concatenate_row = np.concatenate((a, b), axis = 0) # Row wise
print(concatenate_row)

concatenate_column = np.concatenate((a, b), axis = 1) # Column wise
print(concatenate_column)

[[ 6  4  7]
 [ 7  6  7]
 [ 1  1  4]
 [13 13 11]
 [16 18 17]
 [19 13 12]]
[[ 6  4  7 13 13 11]
 [ 7  6  7 16 18 17]
 [ 1  1  4 19 13 12]]


In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
transpose = mat.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.random.randint(1, 10, size = (10, 5))
print(arr)

print()

splitted_array = np.array_split(arr, 3)
print(splitted_array)

[[6 4 5 4 7]
 [9 2 3 8 2]
 [6 3 8 9 1]
 [7 4 9 7 5]
 [1 9 5 9 2]
 [4 5 2 7 1]
 [3 1 8 1 9]
 [1 4 2 3 8]
 [1 6 4 1 9]
 [2 5 8 9 9]]

[array([[6, 4, 5, 4, 7],
       [9, 2, 3, 8, 2],
       [6, 3, 8, 9, 1],
       [7, 4, 9, 7, 5]]), array([[1, 9, 5, 9, 2],
       [4, 5, 2, 7, 1],
       [3, 1, 8, 1, 9]]), array([[1, 4, 2, 3, 8],
       [1, 6, 4, 1, 9],
       [2, 5, 8, 9, 9]])]


Ndarray Arithmetic Operators

In [ ]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([1, 2, 3, 4, 5])

add = x + y
print(add)

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

rem = x % y
print(rem)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[0 0 0 0 0]


In [ ]:
x = np.array([30, 60, 90, 120, 150])

sqrt = np.sqrt(x)
print(sqrt)

sin_val = np.sin(x) # radian
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)

deg = np.rad2deg(x)
print(deg)

rad = np.deg2rad(x)
print(rad)

log_val = np.log(x)
print(log_val)

log_val_base_2 = np.log2(x)
print(log_val_base_2)

[ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
[-0.98803162 -0.30481062  0.89399666  0.58061118 -0.71487643]
[ 0.15425145 -0.95241298 -0.44807362  0.81418097  0.69925081]
[-6.4053312   0.32004039 -1.99520041  0.71312301 -1.02234624]
[1718.87338539 3437.74677078 5156.62015618 6875.49354157 8594.36692696]
[0.52359878 1.04719755 1.57079633 2.0943951  2.61799388]
[3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
[4.9068906  5.9068906  6.4918531  6.9068906  7.22881869]


Broadcasting

In [ ]:
x = np.array([10, 20, 30, 40, 50])
result = x + 2
print(result)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
result = matrix + 2
print(result)

vector = np.array([1, 2, 3])
result = matrix + vector
print(result)

[12 22 32 42 52]
[[3 4 5]
 [6 7 8]]
[[2 4 6]
 [5 7 9]]


Logical operations

In [ ]:
x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 4, 5])

greater_than = x > y
print(greater_than)

print(np.all(greater_than))
print(np.any(greater_than))

less_than = x < y
print(less_than)

equal = x==y
print(equal)

not_equal = x!=y
print(not_equal)

[ True  True  True  True]
True
True
[False False False False]
[False False False False]
[ True  True  True  True]


Sorting

In [ ]:
x  = np.array([10, 8, 16, 100])
z = x.copy()
print(z)

z.sort()
print(z)

sort_arr = np.sort(x)
print(sort_arr)

[ 10   8  16 100]
[  8  10  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
mat = np.array([[10, 3, 5], [8, 4, 9]])
hor_sort = np.sort(mat, axis = 0)
print(hor_sort)

vert_sort = np.sort(mat, axis = 1)
print(vert_sort)

[[ 8  3  5]
 [10  4  9]]
[[ 3  5 10]
 [ 4  8  9]]


Ndarray Searching

In [ ]:
import numpy as np

x = np.array([10, 8, 16, 100])
index = np.where(x == 16)
print(index)

index = np.where(x > 8)
print(index)

arr = np.where(x > 15, x, 0) # If condition is false replace with zero
print(arr)

maximum_value_index = np.argmax(x)
print(maximum_value_index)

minimum_value_index = np.argmin(x)
print(minimum_value_index)

(array([2]),)
(array([0, 2, 3]),)
[  0   0  16 100]
3
1


Ndarray Counting

In [ ]:
a = np.random.randint(1, 100, size = (100,))
print(a)

value_greater_than_50 = np.count_nonzero(a > 50)
print(value_greater_than_50)

unique_values, counts = np.unique(a, return_counts = True)
print(counts)
print(unique_values)

[ 9 79 82 13 17 16 39 18 96 86 26 83 42 34 26 69 60  8 36 90 98 83 57  6
 79 79 60 15 29 20  4 45  3 18 85 49  2 51 62 33 97 57 19 47 64 10 43  1
 10 64 15 78 68 81 88 94 92 42 34  3 36  5 63 73 54 20 69  5 42 22 37 34
 95 86 26 61 16 18 48 49 76 32 66 91 88 10 86 90 65 10 73 63 42  5 75  9
 37 75 59 57]
47
[1 1 2 1 3 1 1 2 4 1 2 2 1 3 1 2 1 3 1 1 1 3 2 2 1 4 1 1 1 1 2 1 1 3 1 2 1
 1 2 2 1 1 1 2 2 2 1 1 3 1 1 2 1 3 2 2 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  8  9 10 13 15 16 17 18 19 20 22 26 29 32 33 34 36 37
 39 42 43 45 47 48 49 51 54 57 59 60 61 62 63 64 65 66 68 69 73 75 76 78
 79 81 82 83 85 86 88 90 91 92 94 95 96 97 98]


Statistical function

In [38]:
import numpy as np

data = np.genfromtxt('/content/sample_data/student_scores.csv', delimiter=',', skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [39]:
math_marks = data[::,:1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.average(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

standard_deviation_math_marks = np.std(math_marks)
print(standard_deviation_math_marks)

science_marks = data[::,1:2]
print(science_marks.T)

english_marks = data[::,2:3]
print(english_marks.T)



[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204
[[85. 67. 92. 52. 75. 90. 60. 57. 89. 70. 69. 82. 64. 78. 93. 71. 79. 86.
  63. 97.]]
[[82. 72. 88. 58. 80. 91. 62. 54. 87. 76. 68. 81. 60. 74. 90. 69. 78. 85.
  65. 96.]]


Linear Algebra with NumPy

In [42]:
study_hours = np.array([2, 4, 6, 8, 10])
exam_scores = np.array([65, 75, 85, 95, 93])

data = np.array([study_hours, exam_scores])
print(data)

correlation = np.corrcoef(data)
print(correlation)

[[ 2  4  6  8 10]
 [65 75 85 95 93]]
[[1.         0.95358267]
 [0.95358267 1.        ]]


In [46]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([[7, 8, 9],
              [11, 12, 13],
              [14, 15, 16]])

dot_product = np.dot(A, B)
print(dot_product)

print(np.trace(A))
print(np.trace(B))

determinant_A = np.linalg.det(A)
print(determinant_A)
determinant_B = np.linalg.det(B)
print(determinant_B)

inverse_B = np.linalg.inv(B)
print(inverse_B)

15
35
[[ 71  77  83]
 [167 182 197]
 [263 287 311]]
0.0
-1.243449787580179e-14
[[ 2.41264266e+14 -5.62949953e+14  3.21685688e+14]
 [-4.82528532e+14  1.12589991e+15 -6.43371375e+14]
 [ 2.41264266e+14 -5.62949953e+14  3.21685688e+14]]
