Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1]) # Slice from the index 3 from the end to index 1 from the end

[2 3 4 5]
[5 6 7]


If we don't pass start its considered 0.

If we don't pass step its considered 1.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:]) # Slice elements from index 4 to the end of the array
print(arr[:4]) # Slice elements from the beginning to index 4 (not included)

[5 6 7]
[1 2 3 4]


Step: [start:end:step]

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) # Return every other element from index 1 to index 5
print(arr[::2]) # Return every other element from the entire array

[2 4]
[1 3 5 7]


Slicing 2-D Arrays

In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included)
print(arr[0:2, 2]) # From both elements, return index 2
print(arr[0:2, 1:4]) # From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
