where() — Returns indices where a condition is True.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
idx = np.where(arr == 2)
print(idx)

arr = np.array([1, 2, 3, 2, 4, 2])
idx = np.where(arr == 2)
print(idx)

arr = np.array([1, 2, 3, 4, 5])
idx = np.where(arr == 6)
print(idx)

(array([1]),)
(array([1, 3, 5]),)
(array([], dtype=int64),)


In [4]:
arr = np.array([10, 20, 5, 30, 2])
print(np.where(arr > 10))

(array([1, 3]),)


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.where(arr % 2 == 0))

(array([1, 3, 5, 7]),)


In [8]:
arr = np.array([1, 2, 3, 4])
arr2 = np.where(arr % 2 == 0, 100, arr)
print(arr2)

[  1 100   3 100]


In [16]:
arr = np.array([[1, 2, 3],
                [4, 2, 6],
                [7, 8, 2]])

print(np.where(arr == 2))
# Output: (array([0, 1, 2]), array([1, 1, 2]))
# Meaning:
# Found at (row 0, col 1)
# Found at (row 1, col 1)
# Found at (row 2, col 2)
print(np.where(arr > 4))

(array([0, 1, 2]), array([1, 1, 2]))
(array([1, 2, 2]), array([2, 0, 1]))


Boolean masking- Extract values that match a condition.

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])
print(arr[arr < 3])
print(arr[arr == 3])

[4 5]
[1 2]
[3]


isin() — Search for multiple values

In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40])
mask = np.isin(arr, [20, 40])
print(mask)
print(arr[mask]) 

[False  True False  True]
[20 40]


argmax() and argmin() — Search for largest/smallest index

In [18]:
import numpy as np

arr = np.array([4, 7, 1, 9, 3])
max_idx = arr.argmax()
print(max_idx)
min_idx = arr.argmin()
print(min_idx)

3
2
