sort() — Returns a sorted copy

In [ ]:
import numpy as np

arr1 = np.array([4, 1, 7, 2])
arr2 = np.sort(arr1)
print(arr2)
print(arr1) # Original array stays unchanged

[1 2 4 7]
[4 1 7 2]


In [15]:
arr = np.array([4, 1, 7, 2])
print(np.sort(arr)[::-1]) # Sorting in descending order

[7 4 2 1]


In [9]:
arr = np.array([4, 1, 7, 2])
arr.sort()
print(arr) # Modifies the original array

[1 2 4 7]


In [4]:
arr = np.array([[3, 1, 2],
                [9, 7, 8]])

print(np.sort(arr))

[[1 2 3]
 [7 8 9]]


In [7]:
arr = np.array([[3, 1, 2],
                [9, 7, 8],
                [4, 5, 6]])

print(np.sort(arr, axis=0))  # Sort column-wise
print(np.sort(arr, axis=1)) # Sort row-wise

[[3 1 2]
 [4 5 6]
 [9 7 8]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [10]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


argsort() — Return sorted indices. It returns the indices that would sort the array in ascending order.
It does not return sorted values — only the order of indices.

In [13]:
import numpy as np

arr = np.array([40, 10, 30])
idx = np.argsort(arr)
print(idx)

arr = np.array([5, 10, 50, 20, 30])
idx = np.argsort(arr)
print(idx)

[1 2 0]
[0 1 3 4 2]


searchsorted()- NumPy’s fast binary-search function, and returns the index where the specified value would be inserted to maintain the search order.

In [16]:
import numpy as np

arr = np.array([1, 3, 5, 7]) # Sorted array
idx = np.searchsorted(arr, 5) # np.searchsorted(sorted_array, value, side='left') side='left' -> First place where value appears
print(idx)
idx = np.searchsorted(arr, 6)
print(idx)

2
3


In [19]:
arr = np.array([6, 7, 8, 9])
idx = np.searchsorted(arr, 7, side='right') # side='right' -> Position after value
print(idx)


2


In [18]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
idxes = np.searchsorted(arr, [5, 20, 45]) # Find the indexes where the values 5, 20, and 45 should be inserted
print(idxes)

arr = np.array([1, 3, 5, 7])
print(np.searchsorted(arr, [2, 4, 6]))

[0 1 4]
[1 2 3]
