Boolean Indexing- A boolean index list is a list of booleans corresponding to indexes in the array. If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
filtered = arr > 3
print(filtered)
print(arr[filtered])

[False False False  True  True]
[4 5]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False  True False  True False  True False]
[2 4 6]


In [9]:
arr = np.array([5, 10, 15, 20, 25])

filtered = arr[(arr > 10) & (arr < 25)]
print(filtered)

[15 20]


In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

filtered = arr[arr > 3]
print(filtered)

[4 5 6]


extract()- Equivalent to boolean indexing

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
filtered = np.extract(arr > 2, arr)
print(filtered)

[3 4 5]


where()- can return indices that satisfy a condition

In [8]:
import numpy as np

arr = np.array([10, 20, 15, 30])
indices = np.where(arr > 15)
filtered = arr[indices]
print(filtered)

[20 30]
