Data Types in NumPy:

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer

    b - boolean

    u - unsigned integer

    f - float

    c - complex float

    m - timedelta

    M - datetime

    O - object

    S - string

    U - unicode string

    V - fixed chunk of memory for other type ( void )

Core NumPy Data Types

    1. Boolean:

        bool_ – Boolean (True/False)

    2. Integers:

    Signed Integers

        int8	8-bit signed integer (−128 to 127)

        int16	16-bit signed integer

        int32	32-bit signed integer

        int64	64-bit signed integer

    Unsigned Integers

        uint8	8-bit unsigned integer (0 to 255)

        uint16	16-bit unsigned

        uint32	32-bit unsigned

        uint64	64-bit unsigned

    3. Floating-Point Numbers:

        float16	Half precision

        float32	Single precision

        float64	Double precision (most common)

        float128	Extended precision (not available on Windows)

    4. Complex Numbers

        complex64	Complex number with 2×32-bit floats

        complex128	2×64-bit floats

        complex256	2×128-bit floats (not available everywhere)

    5. String & Unicode

        bytes_	Fixed-length byte string

        str_	Fixed-length Unicode string

        NumPy strings are fixed-size, unlike Python strings.

    6. Object

        object_	Arbitrary Python objects

        Used when array elements are not uniform (e.g., mixed data types).

    7. Datetime and Timedelta

        datetime64	Represents dates/timestamps

        timedelta64	Time differences/durations

    These support very precise units:

        datetime64[s], datetime64[ms], etc.

    8. Void (Raw Bytes)

        void   Raw, fixed-size bytes (used in structured arrays)

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [12]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


Create arrays with specific integer types

In [14]:
a = np.array([10, 20, 30], dtype=np.int8)
b = np.array([10, 20, 30], dtype=np.uint16)

print(a, a.dtype)
print(b, b.dtype)

[10 20 30] int8
[10 20 30] uint16


In [15]:
f1 = np.array([1.2, 3.4], dtype=np.float32)
f2 = np.array([1.2, 3.4], dtype=np.float64)

print(f1.dtype)
print(f2.dtype) 

float32
float64


In [16]:
c = np.array([1+2j, 3+4j], dtype=np.complex128)
print(c)
print(c.dtype)

[1.+2.j 3.+4.j]
complex128


In [17]:
bool_arr = np.array([True, False, True], dtype=bool)
print(bool_arr, bool_arr.dtype)

[ True False  True] bool


In [18]:
s = np.array(["apple", "banana"], dtype="U10")
print(s, s.dtype)

['apple' 'banana'] <U10


In [19]:
b = np.array([b"hi", b"there"], dtype="S5")
print(b, b.dtype)

[b'hi' b'there'] |S5


Converting Data Type on Existing Arrays

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int64
