0-D Arrays: 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [13]:
import numpy as np
arr = np.array(42)
print(arr)
print(arr.ndim)
print(arr.shape)

42
0
()


1-D Arrays: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


2-D Arrays: An array that has 1-D arrays as its elements is called a 2-D array. NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Reshape From 1-D to 2-D:


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4, 3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3-D arrays: An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6]], 
                [[1, 2, 3], 
                 [4, 5, 6]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(2, 2, 3)


Reshape From 1-D to 3-D

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(2, 3, 2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Higher Dimensional Arrays: An array(ndarray) can have any number of dimensions. In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


Unknown Dimension

In [4]:
import numpy as np

# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# newarr = arr.reshape(3, 3) # Error- Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
# print(newarr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1) # Pass -1 as the value, and NumPy will calculate this number for us.
print(newarr) # We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening the arrays: multidimensional array into a 1D array.

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = arr.reshape(-1)
print(new_arr)

[1 2 3 4 5 6]
