concatenate(): Use this when we want to join arrays along an existing axis.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0) # Join along rows (axis=0)
print(arr)
arr = np.concatenate((arr1, arr2), axis=1) # Join along columns (axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


| Axis | Direction                                                  |
| ---- | -----------------------------------------------------------|
| 0    | **Down the rows** (vertical)  (columns stay fixed)         |
| 1    | **Across the columns** (horizontal)     (rows stay fixed)  |
| 2    | **Depth / 3rd dimension** (for 3D arrays)                  |


stack(): his creates a higher-dimensional array. It does not merge data; it groups them.

In [20]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1,arr2))
print(arr)

print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [2]:
import numpy as np

arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
new_arr1 = np.stack((arr1, arr2), axis=0)
print(new_arr1) # Join with a new axis at position 0
print("\n")
new_arr2 = np.stack((arr1, arr2), axis=1)
print(new_arr2) # Join with a new axis at position 1

print(new_arr1.ndim)
print(new_arr2.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
3
3


Horizontal(hstack()), Vertical(vstack()), Depth joins(dstack()):

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


column_stack() and row_stack():

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.column_stack((arr1, arr2))
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
arr = np.row_stack((arr1, arr2)) # same as vstack
print(arr)

[[1 2 3]
 [4 5 6]]


C:\Users\Tanvir Hossain\AppData\Local\Temp\ipykernel_33160\2350701860.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr = np.row_stack((arr1, arr2)) # same as vstack


When to use what (straightforward rule)?

Join along existing axis-	    concatenate

Add a new axis while joining-	stack

Horizontal join (col-wise)-	    hstack

Vertical join (row-wise)-	    vstack

Make 3-D depth join-	            dstack

Join column vectors-	            column_stack