What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Random numbers generated through a generation algorithm are called pseudo random.

Generate random float:

In [13]:
import numpy as np

np.random.rand()  # Generate a random float number between 0 and 1

0.4105334577003623

In [14]:
np.random.rand(5)  # 1D array of 5 floats (between 0 and 1)

array([0.75306286, 0.54119492, 0.06697606, 0.3179061 , 0.99454979])

In [15]:
np.random.rand(2, 3)  # 2x3 array

array([[0.82014492, 0.19800941, 0.18437502],
       [0.40364305, 0.17559497, 0.79876524]])

In [16]:
import numpy as np

random_number_generator = np.random.default_rng()

random_number_generator.random()
random_number_generator.random(5)
random_number_generator.random((2, 3))

array([[0.71750364, 0.35765261, 0.85489081],
       [0.97085606, 0.53392337, 0.90870748]])

In [33]:
from numpy import random

num = random.rand() # Generate a random float number between 0 and 1
print(num)
arr = random.rand(5) # 1D array of 5 floats (between 0 and 1)
print(arr)
arr = random.rand(2, 3) # 2x3 array 
print(arr)

0.7951629542864246
[0.95026479 0.7971203  0.18041834 0.7841271  0.66735515]
[[0.95812982 0.23677072 0.59627303]
 [0.95755342 0.81501875 0.14395552]]


Random integers:

In [32]:
from numpy import random

num = random.randint(10) # Generate a random integer number between 0 and 10
print(num)
num = random.randint(1, 10) # Generate a random integer number between 1 and 10
print(num)
arr = random.randint(1, 10, size=5) # 1D array of 5 integers between 1 and 10
print(arr)
arr = random.randint(1, 10, size=(2,3)) # 2x3 array 
print(arr)

3
5
[2 2 6 2 9]
[[7 6 6]
 [9 1 7]]


choice()- allows us to generate a random value based on an array of values.

In [39]:
from numpy import random

num = random.choice([3, 5, 7, 9])
print(num)
arr = random.choice([3, 5, 7, 9], size=(3, 5))
print(arr)

5
[[9 5 7 5 9]
 [3 5 3 7 7]
 [5 9 7 5 9]]
