Ndarray (N-Dimensional Array)

In [ ]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(type(arr1)) # ndarray = N-dimensional array
print(arr1)
print(arr1.ndim)


# 2D array
arr2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.ndim)

# 3D array
arr3 = np.array([[[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]],
                [[11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20]]])
print(arr3)
print(arr3.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


Attributes

In [ ]:
print(type(arr1)) # ndarray = N-dimensional array
print(type(arr2))
print(type(arr3))

print(arr1.dtype)
print(arr1.dtype)
print(arr1.dtype)

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
int64
int64
1
2
3
5
10
20
(5,)
(2, 5)
(2, 2, 5)


Ndarray Data Type

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1.dtype)

arr2 = np.array([1, 2, 4.5, 6.3]) # Upcasting
print(arr2.dtype)

arr3 = np.array([1, 2, 3.5, "Hello"]) # Upcasting
print(arr3.dtype)

arr = np.array([1, 2, 3], dtype=np.int8)
print(arr.dtype)

# arr = np.array([1, 2, 3, 300], dtype=np.int8)
# print(arr.dtype) # Overflow

int64
float64
<U32
int8


Creating ndarray from scratch

In [22]:
import numpy as np

# Example 1: Create a 2x3 array filled with zeros
arr1 = np.zeros((2, 3), dtype=np.int64)  # shape = (2, 3), all elements = 0
print("Example 1: np.zeros()")
print(arr1)
print("Data type:", arr1.dtype)
print()

# Example 2: Create a 3D array and fill it with zeros using np.zeros_like()
original = np.array([
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]
])

arr2 = np.zeros_like(original)  # same shape and dtype as 'original', but all zeros
print("Example 2: np.zeros_like()")
print(arr2)
print("Shape:", arr2.shape)
print("Data type:", arr2.dtype)
print()

# Example 3: Using float dtype
arr3 = np.zeros((3, 4))
print("Example 3: np.zeros() with float dtype")
print(arr3)
print("Data type:", arr3.dtype)


Example 1: np.zeros()
[[0 0 0]
 [0 0 0]]
Data type: int64

Example 2: np.zeros_like()
[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]
Shape: (2, 2, 5)
Data type: int64

Example 3: np.zeros() with float dtype
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Data type: float64


In [23]:
import numpy as np

# Example 1: Create a 2x3 array filled with ones
arr1 = np.ones((2, 3), dtype=np.int64)  # shape = (2, 3), all elements = 1
print("Example 1: np.ones()")
print(arr1)
print("Data type:", arr1.dtype)
print()

# Example 2: Create a 3D array and fill it with ones using np.ones_like()
original = np.array([
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]
])

arr2 = np.ones_like(original)  # same shape and dtype as 'original', but all ones
print("Example 2: np.ones_like()")
print(arr2)
print("Shape:", arr2.shape)
print("Data type:", arr2.dtype)
print()

# Example 3: Using float dtype
arr3 = np.ones((3, 4))
print("Example 3: np.ones() with float dtype")
print(arr3)
print("Data type:", arr3.dtype)


Example 1: np.ones()
[[1 1 1]
 [1 1 1]]
Data type: int64

Example 2: np.ones_like()
[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
Shape: (2, 2, 5)
Data type: int64

Example 3: np.ones() with float dtype
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Data type: float64


In [35]:
import numpy as np

# Example : Create a 2x3 array using np.empty()
arr1 = np.empty((2, 3), dtype = np.int64)
print(arr1)
print("Data type:", arr1.dtype)
print()

# Difference between zeros(), ones(), and empty()
print("np.zeros((2,2)):\n", np.zeros((2, 2)))
print("np.ones((2,2)):\n", np.ones((2, 2)))
print("np.empty((2,2)):\n", np.empty_like((2, 2)))  # may contain random memory values


[[7 7 7]
 [7 7 7]]
Data type: int64

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.empty((2,2)):
 [2 3]


In [32]:
import numpy as np

# Example: Create a 2x3 array filled with a specific value (e.g., 7)
arr1 = np.full((2, 3), 7, dtype = np.int64)
print("Example: np.full()")
print(arr1)
print("Data type:", arr1.dtype)
print()

# Comparison between zeros(), ones(), and full()
print("Comparison")
print("np.zeros((2,2)):\n", np.zeros((2, 2)))
print("np.ones((2,2)):\n", np.ones((2, 2)))
print("np.full((2,2), 5):\n", np.full((2, 2), 5))


Example: np.full()
[[7 7 7]
 [7 7 7]]
Data type: int64

Comparison
np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.full((2,2), 5):
 [[5 5]
 [5 5]]


Ndarray creation with random values

In [43]:
import numpy as np

arr = np.random.rand(3, 3) # 0 to 1 floating random values
print(arr)

arr1 = np.random.randint(1, 10, (3, 3))
print(arr1)

arr2 = np.random.uniform(1, 10, (3, 3))
print(arr2)

[[0.17729334 0.50457421 0.42683438]
 [0.44645927 0.16928053 0.31470337]
 [0.10584182 0.23381924 0.92357371]]
[[8 1 4]
 [2 5 7]
 [5 4 6]]
[[2.22379508 3.52633325 6.15579557]
 [9.80333813 3.15011604 5.066011  ]
 [1.35170693 6.71088288 4.15655141]]


Ndarray Creation with range functions

In [56]:
import numpy as np

arr = np.arange(1, 19, 2)
matrix = arr.reshape(3, 3)
print(arr)
print(matrix)

arr2 = np.linspace(1, 10, 5)
print(arr2)

arr3 = np.logspace(1, 10, 5)
print(arr3)

arr4 = np.logspace(1, 10, 5, base = 2)
print(arr4)

[ 1  3  5  7  9 11 13 15 17]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 1.    3.25  5.5   7.75 10.  ]
[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]
[   2.            9.51365692   45.254834    215.2694823  1024.        ]


Creating matrix for linear algebra

In [61]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)
print(diagonal_matrix.shape)

identity_matrix = np.eye(3)
print(identity_matrix)
print(identity_matrix.shape)

identity_matrix = np.eye(3, 4)
print(identity_matrix)
print(identity_matrix.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
(3, 4)


Ndarray Idexing and Slicing

In [71]:
import numpy as np

arr = np.arange(1, 19, 2)
matrix = arr.reshape(3, 3)
print(matrix)

print(matrix[2][0])
matrix[2][0] = 14
print(matrix)

matrix_slice = arr[1:4]
print(matrix_slice)

matrix_slice2 = arr[1:2]
print(matrix_slice2)

# matrix_2d_slice = matrix[0:2, 0:2]
matrix_2d_slice = matrix[:2, :2]
print(matrix_2d_slice)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
13
[[ 1  3  5]
 [ 7  9 11]
 [14 15 17]]
[3 5 7]
[3]
[[1 3]
 [7 9]]


In [76]:
import numpy as np

arr = np.arange(1, 19, 2)
matrix = arr.reshape(3, 3)
print(matrix)

print(matrix[2][0])
matrix[2][0] = 14
print(matrix)

matrix_slice = arr[1:4]
print(matrix_slice)

print(matrix) # Not changed

matrix_slice = arr[1:4].copy() # Changed
matrix[2][0] = 14
print(matrix)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
13
[[ 1  3  5]
 [ 7  9 11]
 [14 15 17]]
[3 5 7]
[[ 1  3  5]
 [ 7  9 11]
 [14 15 17]]
[[ 1  3  5]
 [ 7  9 11]
 [14 15 17]]


In [85]:
lst = np.array([10, 20, 30, 40, 50])
values = lst[[2, 3, 4]]
print(values)

lst = np.array([[10, 20, 30], [40, 50, 60]])
values2 = lst[[0, 1], [2, 1]]
print(values2)

print(lst[lst > 20])

[30 40 50]
[30 50]
[30 40 50 60]


In [87]:
lst = np.array([[10, 20, 30], [40, 50, 60]])

# for i in lst:
#   for j in i:
#     print(j)

for i in np.nditer(lst):
  print(i)

10
20
30
40
50
60
